server:
  port : 8081
  servlet:
    context-path: /idp

spring:
  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    username: psqluser
    password: psqlpwd
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth_db
    initialization-mode: always

logging:
  level:
    org:
      springframework:
        security: DEBUG
